[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1_000_000
verbosity = 3
ignored_error_codes = []

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 50

[profile.default.model_checker]
engine = "chc"
solvers = ["z3"]
timeout = 100_000
contracts = {"./src/ERC721Harberger.sol" = ["ERC721Harberger"]}
invariants = [
    "contract",
#    "reentrancy"
]
targets = [
    "assert",
#    "underflow",
#    "overflow",
#    "divByZero"
]
show_unproved = true
show_unsupported = true
show_proved_safe = true

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
invariant_runs = 10_000

[profile.coverage]
optimizer = false
via_ir = false

[fmt]
line_length = 120
wrap_comments = true
number_underscores = "thousands"
bracket_spacing = true
int_types = "long"
