[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 1_000_000
verbosity = 3

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 50

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
invariant_runs = 10_000

[profile.coverage]
optimizer = false
via_ir = false

[fmt]
line_length = 120
wrap_comments = true
number_underscores = "thousands"
bracket_spacing = true
int_types = "long"
